# Generated by Django 5.2.7 on 2025-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_property_remove_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
