# Generated by Django 5.2.7 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_property_updated_at_alter_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=50),
        ),
    ]
